model_name_or_path: /root/group-shared/jrc/base_models/Qwen3-14B
output_dir: /root/group-shared/jrc/trained_models/iteration_4_generation_8_extended
dataset_name: /root/workspace/PRewrite/data/extended_dataset
dataset_config: default
dataset_train_split: train
dataset_test_split: test
learning_rate: 1e-6
gradient_checkpointing: true
dtype: bfloat16
max_prompt_length: 2048
max_completion_length: 2048
use_vllm: true
vllm_mode: colocate
log_completions: true
# reward functions settings
reward_funcs:
  - accuracy_math_reward
  - accuracy_classification_reward
  - f1_classification_reward
  - accuracy_nq_open_instruction_prewrite_reward
  - f1_nq_open_instruction_prewrite_reward
reward_weights:
  - 1.0
  - 0.0
  - 1.0
  - 0.0
  - 1.0
generate_model_name_or_path: /root/group-shared/jrc/base_models/Qwen3-32B
generate_model_ip: 0.0.0.0
generate_model_port: 33337
generate_model_offline: false
test_size: 16
generate_dataset_seed: 42
# vllm settings
use_vllm: true
vllm_mode: colocate
vllm_tensor_parallel_size: 8
vllm_gpu_memory_utilization: 0.25
num_generations: 8
temperature: 1.0
use_liger_kernel: true
use_liger_loss: false
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 2
loss_type: dapo
epsilon: 0.2
epsilon_high: 0.28
num_iterations: 4
num_train_epochs: 1000
eval_strategy: "no"
eval_steps: 1
save_strategy: "steps"
save_steps: 50
save_total_limit: 1
logging_steps: 1
report_to:
  - tensorboard
project_name: PRewrite
run_name: iteration_4_generation_8_extended